CREATE TABLE IF NOT EXISTS audit_scope_targets (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  audit_id BIGINT UNSIGNED NOT NULL,
  process_id BIGINT UNSIGNED NOT NULL,
  cert_goal_level TINYINT UNSIGNED NOT NULL,
  custom_goal_level TINYINT UNSIGNED NULL,
  scope_option_id TINYINT UNSIGNED NOT NULL,
  archived_at_UTC DATETIME(3) NULL,
  created_at_UTC DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3),
  updated_at_UTC DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3) ON UPDATE UTC_TIMESTAMP(3),
  updated_by BIGINT UNSIGNED NULL,
  active_audit_id BIGINT UNSIGNED AS (CASE WHEN archived_at_UTC IS NULL THEN audit_id ELSE NULL END) STORED,
  active_process_id BIGINT UNSIGNED AS (CASE WHEN archived_at_UTC IS NULL THEN process_id ELSE NULL END) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY uq_audit_scope_targets_active (active_audit_id, active_process_id),
  KEY idx_audit_scope_targets_audit (audit_id),
  KEY idx_audit_scope_targets_process (process_id),
  CONSTRAINT fk_audit_scope_targets_audit FOREIGN KEY (audit_id) REFERENCES audits(id),
  CONSTRAINT fk_audit_scope_targets_process FOREIGN KEY (process_id) REFERENCES processes(id),
  CONSTRAINT fk_audit_scope_targets_cert_goal FOREIGN KEY (cert_goal_level) REFERENCES target_levels(level),
  CONSTRAINT fk_audit_scope_targets_custom_goal FOREIGN KEY (custom_goal_level) REFERENCES target_levels(level),
  CONSTRAINT fk_audit_scope_targets_scope_option FOREIGN KEY (scope_option_id) REFERENCES scope_options(id),
  CONSTRAINT fk_audit_scope_targets_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
