CREATE TABLE IF NOT EXISTS audit_assessments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  audit_id BIGINT UNSIGNED NOT NULL,
  requirement_id BIGINT UNSIGNED NOT NULL,
  capability_score_id TINYINT UNSIGNED NULL,
  comment_text TEXT NULL,
  evidence_text TEXT NULL,
  pii_redacted_at_UTC DATETIME(3) NULL,
  archived_at_UTC DATETIME(3) NULL,
  created_at_UTC DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3),
  updated_at_UTC DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3) ON UPDATE UTC_TIMESTAMP(3),
  updated_by BIGINT UNSIGNED NULL,
  active_audit_id BIGINT UNSIGNED AS (CASE WHEN archived_at_UTC IS NULL THEN audit_id ELSE NULL END) STORED,
  active_requirement_id BIGINT UNSIGNED AS (CASE WHEN archived_at_UTC IS NULL THEN requirement_id ELSE NULL END) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY uq_audit_assessments_active (active_audit_id, active_requirement_id),
  KEY idx_audit_assessments_audit (audit_id),
  KEY idx_audit_assessments_requirement (requirement_id),
  KEY idx_audit_assessments_score (capability_score_id),
  CONSTRAINT fk_audit_assessments_audit FOREIGN KEY (audit_id) REFERENCES audits(id),
  CONSTRAINT fk_audit_assessments_requirement FOREIGN KEY (requirement_id) REFERENCES requirements(id),
  CONSTRAINT fk_audit_assessments_capability_score FOREIGN KEY (capability_score_id) REFERENCES capability_scores(id),
  CONSTRAINT fk_audit_assessments_updated_by FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
