CREATE TABLE IF NOT EXISTS audit_pdf_exports (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  audit_id BIGINT UNSIGNED NOT NULL,
  org_id BIGINT UNSIGNED NOT NULL,
  report_kind ENUM('FULL_ASSESSMENT_REPORT') NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_path VARCHAR(1024) NOT NULL,
  file_size_bytes BIGINT UNSIGNED NOT NULL,
  sha256_hex CHAR(64) NOT NULL,
  is_current TINYINT(1) NOT NULL DEFAULT 1,
  archived_at DATETIME(3) NULL,
  generated_at DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3),
  generated_by BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT UTC_TIMESTAMP(3) ON UPDATE UTC_TIMESTAMP(3),
  active_audit_id BIGINT UNSIGNED AS (CASE WHEN archived_at IS NULL THEN audit_id ELSE NULL END) STORED,
  active_report_kind VARCHAR(64) AS (CASE WHEN archived_at IS NULL THEN report_kind ELSE NULL END) STORED,
  active_is_current TINYINT(1) AS (CASE WHEN archived_at IS NULL AND is_current = 1 THEN 1 ELSE NULL END) STORED,
  PRIMARY KEY (id),
  KEY idx_audit_pdf_exports_audit_generated (audit_id, generated_at),
  KEY idx_audit_pdf_exports_org_generated (org_id, generated_at),
  KEY idx_audit_pdf_exports_generated_by (generated_by),
  UNIQUE KEY uq_audit_pdf_exports_current_per_kind (active_audit_id, active_report_kind, active_is_current),
  CONSTRAINT fk_audit_pdf_exports_audit FOREIGN KEY (audit_id) REFERENCES audits(id),
  CONSTRAINT fk_audit_pdf_exports_org FOREIGN KEY (org_id) REFERENCES organizations(id),
  CONSTRAINT fk_audit_pdf_exports_generated_by FOREIGN KEY (generated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
